/* eslint-disable */ // WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsConfig = {
  Auth: {
    mandatorySignIn: true,

    // REQUIRED - Amazon Cognito Region
    region: 'us-east-2',

    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: 'us-east-2_JO965QtEP',

    // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
    userPoolWebClientId: '2lhdpnuct7nfirl2q8fkq8i2ie',
    oauth: {
      domain: 'groov.auth.us-east-2.amazoncognito.com',
      scope: ['email', 'openid', 'profile'],
      redirectSignIn: 'https://www.groov.bio/account/',
      redirectSignOut: 'https://www.groov.bio/',
      responseType: 'code',
    },
    signUpVerificationMethod: 'code',
  },
};
export default awsConfig;
