name: Cypress Tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            ~/.npm
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Install dependencies (cache hit)
        if: steps.npm-cache.outputs.cache-hit == 'true'
        run: echo "Using cached dependencies"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          # Skip install since we already did it with caching
          install: false
          # Run against dev server for speed (no build needed)
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
          browser: chrome
          record: false
          config: video=false,screenshotOnRunFailure=false
        env:
          CI: true
          # Optimize for speed
          GENERATE_SOURCEMAP: false
          FAST_REFRESH: false
